#!/usr/bin/env python3
"""
Generate comprehensive 1000-entry training dataset for iconcern SVM model
"""

import csv
import random

# Training data templates with variations
training_templates = {
    'MIS Office': [
        "I cannot connect to the internet",
        "The WiFi network is not working",
        "I need help with network connection",
        "The internet connection is very slow",
        "I cannot access the school network",
        "The network maintenance is affecting my work",
        "I need help with internet connectivity issues",
        "The WiFi password is not working",
        "I cannot connect to the campus network",
        "The internet is down in my area",
        "I need assistance with network setup",
        "The network connection keeps dropping",
        "I cannot access online resources due to network issues",
        "The internet speed is too slow",
        "I need help troubleshooting network problems",
        "The WiFi signal is weak in my location",
        "I cannot connect my device to the network",
        "The network maintenance needs to be done",
        "I need help with internet configuration",
        "The network is not responding",
        "I cannot access the internet in the computer lab",
        "The WiFi network needs maintenance",
        "I need help with network authentication",
        "The internet connection is unstable",
        "I cannot connect to the school WiFi",
        "The network infrastructure needs repair",
        "I need assistance with network troubleshooting",
        "The internet is not working in the building",
        "I cannot access online services due to network failure",
        "The WiFi network is down",
        "I need help with network connectivity",
        "The internet connection requires maintenance",
        "I cannot connect to the campus internet",
        "The network system needs updating",
        "I need help with network access",
        "The WiFi is not functioning properly",
        "I cannot access the internet network",
        "The network maintenance is required",
        "I need assistance with internet connection",
        "The network connection is not available",
        "I cannot connect to the school internet",
        "The WiFi network needs fixing",
        "I need help with network issues",
        "The internet connectivity is poor",
        "I cannot access network resources",
        "The network maintenance should be handled",
        "I need help with internet network problems",
        "The WiFi connection is not stable",
        "I cannot connect to the network properly",
        "The network maintenance needs attention",
        "Kaluya san portal",
        "Dire maka log in sa portal",
        "Dire maka log in sa portal san student",
        "Dire maka log in sa LMS",
        "Kaluya san mga internet",
        "Kaluya san internet sa lab",
        "Rubat an mga UTP cable",
        "Narubat an mga UTP cable"
    ],
    'IMCO Office': [
        "I need to report a school problem",
        "I have a concern about school dissemination",
        "I need help with a school issue",
        "I want to report a problem affecting students",
        "I need assistance with school-related concerns",
        "I have a problem that needs to be disseminated",
        "I need help addressing a school problem",
        "I want to report an issue to the school",
        "I need help with school problem resolution",
        "I have a concern that needs school attention",
        "I need assistance with school dissemination",
        "I want to report a problem in the school",
        "I need help with school problem handling",
        "I have an issue that needs to be addressed",
        "I need help with school concern reporting",
        "I want to report a school-related problem",
        "I need assistance with problem dissemination",
        "I have a problem that needs school help",
        "I need help with school issue resolution",
        "I want to report a concern to the school",
        "I need help with school problem management",
        "I have an issue that needs dissemination",
        "I need assistance with school problem handling",
        "I want to report a problem that affects the school",
        "I need help with school concern management",
        "I have a problem that needs immediate attention",
        "I need help with school issue reporting",
        "I want to report a school problem",
        "I need assistance with problem resolution",
        "I have a concern that needs to be disseminated",
        "I need help with school problem addressing",
        "I want to report an issue that needs school help",
        "I need help with school concern handling",
        "I have a problem that requires school attention",
        "I need assistance with school problem resolution",
        "I want to report a school-related concern",
        "I need help with problem dissemination to school",
        "I have an issue that needs school assistance",
        "I need help with school problem management",
        "I want to report a concern that affects students",
        "I need assistance with school issue handling",
        "I have a problem that needs to be reported",
        "I need help with school problem addressing",
        "I want to report a school issue",
        "I need help with school concern resolution",
        "I have a problem that needs dissemination",
        "I need assistance with school problem reporting",
        "I want to report a concern to be disseminated",
        "I need help with school problem handling",
        "I have an issue that needs school attention"
    ],
    'Registrar Office': [
        "I need to request my transcript of records",
        "I need help with my student records",
        "I want to check my grades",
        "I need to file a petition for grade change",
        "I need help with subject loading",
        "I want to request my academic records",
        "I need to update my student information",
        "I need help with course registration",
        "I want to request a copy of my grades",
        "I need help with enrollment records",
        "I need to file a petition for subject addition",
        "I want to check my academic standing",
        "I need help with student record keeping",
        "I need to request my official transcript",
        "I want to verify my grades",
        "I need help with subject enrollment",
        "I need to file a petition for course change",
        "I want to request my student records",
        "I need help with grade verification",
        "I need to update my enrollment information",
        "I want to request a transcript",
        "I need help with academic record management",
        "I need to file a petition for grade reconsideration",
        "I want to check my course records",
        "I need help with student information update",
        "I need to request my academic transcript",
        "I want to verify my student records",
        "I need help with subject loading process",
        "I need to file a petition for record correction",
        "I want to request my enrollment records",
        "I need help with grade record keeping",
        "I need to update my academic records",
        "I want to request a copy of my transcript",
        "I need help with student record verification",
        "I need to file a petition for subject change",
        "I want to check my enrollment status",
        "I need help with transcript processing",
        "I need to request my official records",
        "I want to verify my academic records",
        "I need help with grade record management",
        "I need to file a petition for record update",
        "I want to request my student transcript",
        "I need help with subject enrollment records",
        "I need to update my grade records",
        "I want to request a transcript of records",
        "I need help with student record maintenance",
        "I need to file a petition for academic records",
        "I want to check my transcript status",
        "I need help with record keeping and management",
        "Maluya an pila san registrar",
        "Kahalaba san pila san registrar"
    ],
    'Internet Laboratory': [
        "I need to use a computer in the laboratory",
        "I need help with computer access in the lab",
        "I want to use the internet laboratory",
        "I need assistance with computer usage",
        "I need help making my student ID",
        "I want to request for student ID creation",
        "I need to use a computer for my project",
        "I need help with laboratory computer access",
        "I want to use the internet lab computers",
        "I need assistance with student ID processing",
        "I need help accessing computers in the lab",
        "I want to use the laboratory for computer work",
        "I need help with student ID application",
        "I need to use a computer for my assignment",
        "I want to request computer access in the lab",
        "I need help with internet laboratory usage",
        "I need assistance with student ID making",
        "I want to use the lab computers",
        "I need help with computer laboratory access",
        "I need to request for student ID",
        "I want to use a computer in the internet lab",
        "I need help with laboratory computer usage",
        "I need assistance with ID card creation",
        "I want to use the computers in the lab",
        "I need help with student ID processing",
        "I need to use the internet laboratory computers",
        "I want to request computer access",
        "I need help with lab computer access",
        "I need assistance with student ID application",
        "I want to use the laboratory computers",
        "I need help with internet lab computer usage",
        "I need to request for ID card making",
        "I want to use a computer for my work",
        "I need help with laboratory access",
        "I need assistance with student ID creation process",
        "I want to use the internet laboratory",
        "I need help with computer lab access",
        "I need to request for student ID card",
        "I want to use computers in the laboratory",
        "I need help with internet lab computer access",
        "I need assistance with ID making process",
        "I want to use the lab for computer work",
        "I need help with laboratory computer reservation",
        "I need to request for student ID processing",
        "I want to use a computer in the lab",
        "I need help with internet laboratory computer usage",
        "I need assistance with student ID card application",
        "I want to use the laboratory for my computer needs",
        "I need help with lab computer access and usage",
        "I need to request for ID card creation"
    ],
    'Cashier Office': [
        "I need to pay my tuition fees",
        "I want to pay my school requirements",
        "I need help with payment processing",
        "I need to pay for my enrollment",
        "I want to know about payment requirements",
        "I need help with fee payment",
        "I need to pay my school fees",
        "I want to process my payment",
        "I need help with tuition payment",
        "I need to pay for my subjects",
        "I want to know the payment procedures",
        "I need help with payment requirements",
        "I need to pay my outstanding balance",
        "I want to make a payment",
        "I need help with fee computation",
        "I need to pay for my registration",
        "I want to process payment for requirements",
        "I need help with payment methods",
        "I need to pay my school dues",
        "I want to know about payment options",
        "I need help with payment processing",
        "I need to pay for my enrollment fees",
        "I want to make payment for requirements",
        "I need help with payment verification",
        "I need to pay my tuition",
        "I want to process my fee payment",
        "I need help with payment clearance",
        "I need to pay for my school requirements",
        "I want to know the payment schedule",
        "I need help with payment receipt",
        "I need to pay my fees",
        "I want to make a payment transaction",
        "I need help with payment confirmation",
        "I need to pay for my enrollment requirements",
        "I want to process payment for fees",
        "I need help with payment documentation",
        "I need to pay my outstanding fees",
        "I want to make payment for my requirements",
        "I need help with payment status",
        "I need to pay for my registration fees",
        "I want to process my payment requirements",
        "I need help with payment inquiry",
        "I need to pay my school payment",
        "I want to make payment for enrollment",
        "I need help with payment procedures",
        "I need to pay for my tuition requirements",
        "I want to process payment transaction",
        "I need help with payment processing and verification",
        "I need to pay my required fees",
        "I want to make payment for school requirements",
        "Kahalaba san pila permi sa cashier",
        "Kahalaba san pila sa cashier kada adlaw",
        "Maluya an pila sa cashier"
    ],
    'Maintenance Office': [
        "I need to report a room that needs repair",
        "The room needs maintenance",
        "I need help with room repair",
        "I want to report a maintenance issue",
        "I need assistance with room maintenance",
        "The classroom needs repair",
        "I need help reporting a repair needed",
        "I want to request room maintenance",
        "I need to report a room problem",
        "The room requires repair work",
        "I need help with maintenance request",
        "I want to report a room that needs fixing",
        "I need assistance with repair services",
        "The room needs to be repaired",
        "I need help with room maintenance request",
        "I want to report maintenance needed",
        "I need to report a repair issue",
        "The classroom requires maintenance",
        "I need help with room repair request",
        "I want to request maintenance service",
        "I need assistance with room fixing",
        "The room needs repair and maintenance",
        "I need help reporting a maintenance problem",
        "I want to report a room repair needed",
        "I need to request room repair",
        "The room requires repair",
        "I need help with maintenance reporting",
        "I want to report a room maintenance issue",
        "I need assistance with repair request",
        "The classroom needs to be fixed",
        "I need help with room maintenance",
        "I want to request repair service",
        "I need to report a maintenance concern",
        "The room needs repair work",
        "I need help with room repair service",
        "I want to report a repair needed",
        "I need assistance with maintenance work",
        "The room requires maintenance",
        "I need help with repair request",
        "I want to report a room that needs repair",
        "I need to request maintenance for room",
        "The classroom needs repair",
        "I need help with room fixing",
        "I want to report maintenance required",
        "I need assistance with room repair work",
        "The room needs to be maintained",
        "I need help with maintenance service request",
        "I want to report a repair issue in room",
        "I need to request room maintenance service",
        "The room requires repair and maintenance",
        "Kabaho san CR",
        "Mabaho san CR",
        "Kahugaw san CR",
        "Mahugaw san CR",
        "Wara tubig an CR",
        "Wara tubig an comfort room",
        "Kapaso san room",
        "Mapaso san room",
        "Rubat an electric san mga room",
        "Narubat an electric san mga room",
        "Kasarang san basurahan",
        "Nasara san basurahan",
        "Kapaso san Socio",
        "Mapaso san Socio",
        "Rubat an mga TV",
        "Narubat an mga TV",
        "Rubat an mga HDMI",
        "Narubat an mga HDMI",
        "Rubat an TV",
        "Narubat an TV",
        "Rubat an HDMI",
        "Narubat an HDMI",
        "Mabaho an CR",
        "Mapaso an room",
        "Rubat an aircon",
        "Narubat an aircon",
        "Kapaso an classroom",
        "Mapaso an classroom",
        "The CR is smelly",
        "The CR is dirty",
        "No water in the CR",
        "The room is hot",
        "The electricity in the rooms is broken",
        "The trash can is broken",
        "The Socio room is hot",
        "The TVs are broken",
        "The HDMI cables are broken",
        "Kabaho san comfort room",
        "Mabaho san comfort room",
        "Kahugaw san comfort room",
        "Mahugaw san comfort room",
        "Wara tubig an comfort room",
        "Kapaso san classroom",
        "Mapaso san classroom",
        "Rubat an electric san mga classroom",
        "Narubat an electric san mga classroom",
        "Kasarang san trash can",
        "Nasara san trash can",
        "Kapaso san Socio room",
        "Mapaso san Socio room",
        "Rubat an TV",
        "Narubat an TV",
        "Rubat an HDMI cable",
        "Narubat an HDMI cable",
        "Mabaho an comfort room",
        "Mapaso an room",
        "Rubat an mga electric",
        "Narubat an mga electric",
        "The bathroom is smelly",
        "The bathroom is dirty",
        "There is no water in the bathroom",
        "The classroom is hot",
        "The electricity in classrooms is broken",
        "The trash bin is broken",
        "The Socio room is hot",
        "The television is broken",
        "The HDMI cable is broken"
    ],
    'ISSC Office': [
        "I need help with student services",
        "I want to inquire about student services",
        "I need assistance with student concerns",
        "I need help with student support",
        "I want to request student services",
        "I need help with student assistance",
        "I need assistance with student inquiries",
        "I want to know about student services",
        "I need help with student service request",
        "I need assistance with student support services",
        "I want to inquire about available services",
        "I need help with student service processing",
        "I need assistance with student needs",
        "I want to request assistance from student services",
        "I need help with student service information",
        "I need assistance with student service inquiry",
        "I want to know about student support services",
        "I need help with student service assistance",
        "I need assistance with student service request",
        "I want to inquire about student assistance",
        "I need help with student services available",
        "I need assistance with student service support",
        "I want to request help from student services",
        "I need help with student service inquiry",
        "I need assistance with student service needs",
        "I want to know about available student services",
        "I need help with student service processing",
        "I need assistance with student service information",
        "I want to inquire about student service support",
        "I need help with student service assistance",
        "I need assistance with student service inquiry",
        "I want to request student service help",
        "I need help with student services support",
        "I need assistance with student service request",
        "I want to know about student service assistance",
        "I need help with student service needs",
        "I need assistance with student service processing",
        "I want to inquire about student service information",
        "I need help with student service support",
        "I need assistance with student service help",
        "I want to request assistance from ISSC",
        "I need help with ISSC services",
        "I need assistance with ISSC office services",
        "I want to inquire about ISSC office",
        "I need help with ISSC office assistance",
        "I need assistance with ISSC student services",
        "I want to know about ISSC office services",
        "I need help with ISSC office support",
        "I need assistance with ISSC services request",
        "Sge sukot la baraydan",
        "I want to complain about something",
        "Dire nahatag student handbook",
        "Wara pa ginahatag nga student handbook",
        "I need my student handbook from ISSC"
    ],
    'Faculty Office': [
        "The instructor is always late to class",
        "The teacher is rude to students",
        "The professor does not explain the lessons clearly",
        "Kaisog san instructor",
        "Kabastos san instructor",
        "I want to complain about my instructor",
        "The teacher shouted at me in class",
        "The professor is unfair in grading",
        "I have a complaint about the faculty",
        "The instructor ignores student questions",
        "The instructor gives unclear instructions",
        "The teacher is always absent",
        "The professor does not return graded work",
        "The instructor humiliates students in class",
        "The teacher is playing favorites with students",
        "The professor does not follow the syllabus",
        "The instructor arrives very late and ends class early",
        "The teacher uses offensive language",
        "The professor is not accepting our valid reasons",
        "The instructor does not answer questions properly",
        "The teacher is not respecting students",
        "I feel disrespected by my instructor",
        "I want to report unprofessional behavior of a teacher",
        "I want to report the instructor for being unfair",
        "The instructor threatened to fail me",
        "The teacher is ignoring my concerns",
        "I want to file a complaint about my professor",
        "The instructor is not following school policies",
        "The teacher is giving biased grades",
        "The professor makes inappropriate comments in class",
        "Kabastos san instructor",
        "Late na an instructor permi sa klase",
        "Dire maaram magtutdo an instructor"
    ]
}

def generate_training_data():
    """Generate 1000 training data entries"""
    data = []
    
    # Distribute entries across categories
    distribution = {
        'MIS Office': 130,
        'IMCO Office': 130,
        'Registrar Office': 160,
        'Internet Laboratory': 150,
        'Cashier Office': 150,
        'Maintenance Office': 150,
        'ISSC Office': 50,
        'Faculty Office': 80
    }
    
    # Waray keywords that should be preserved exactly
    waray_keywords = [
        'kabaho', 'mabaho', 'kahugaw', 'mahugaw',
        'wara', 'kaluya', 'pila',
        'kapaso', 'mapaso', 'rubat', 'narubat',
        'kasarang', 'nasara', 'sge', 'kaisog', 'kabastos', 'baraydan',
        'basurahan', 'socio', 'cr', 'comfort room', 'cashier', 'registrar'
    ]
    
    for category, count in distribution.items():
        templates = training_templates[category]
        
        # Separate Waray templates from English templates
        waray_templates = [t for t in templates if any(keyword in t.lower() for keyword in waray_keywords)]
        english_templates = [t for t in templates if not any(keyword in t.lower() for keyword in waray_keywords)]
        
        # Ensure Waray templates are included (at least all of them, cycle if needed)
        entries_added = 0
        
        # Add Waray templates first (cycle through them to fill count)
        if waray_templates and len(waray_templates) > 0:
            # Use Waray templates, cycling if needed to reach count
            for i in range(count):
                base_template = waray_templates[i % len(waray_templates)]
                data.append([base_template, category])
                entries_added += 1
        
        # Fill remaining with English templates if needed
        english_count = count - entries_added
        if english_count > 0:
            if english_templates and len(english_templates) > 0:
                for i in range(english_count):
                    base_template = random.choice(english_templates)
                    variations = [
                        base_template,
                        base_template + " Please help me.",
                        base_template + " I need assistance urgently.",
                        "Hello, " + base_template.lower(),
                        base_template + " Thank you.",
                        "I would like to report that " + base_template.lower(),
                        base_template + " This is affecting my studies.",
                        "Good day, " + base_template.lower(),
                        base_template + " I hope you can help.",
                        base_template + " This is urgent."
                    ]
                    concern_text = random.choice(variations)
                    data.append([concern_text, category])
            else:
                # If no English templates, cycle through Waray templates again
                if waray_templates and len(waray_templates) > 0:
                    for i in range(english_count):
                        base_template = waray_templates[i % len(waray_templates)]
                        data.append([base_template, category])
    
    # Shuffle the data
    random.shuffle(data)
    
    return data

def main():
    """Main function to generate CSV"""
    print("Generating 1000-entry training dataset...")
    data = generate_training_data()
    
    # Write to CSV
    csv_file = 'training_data.csv'
    with open(csv_file, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['concern_text', 'label'])  # Header
        writer.writerows(data)
    
    print(f"Successfully generated {len(data)} training entries in {csv_file}")
    print("\nCategory distribution:")
    from collections import Counter
    labels = [row[1] for row in data]
    for category, count in Counter(labels).items():
        print(f"  {category}: {count}")

if __name__ == "__main__":
    main()

